rifat:
  name: Rifat Najmi
  role: Inisiator, Koordinator utama
  bio: Rifat adalah desainer produk dan profesional aksesibilitas bersertifikasi CPACC dari IAAP. Ia menginisiasi situs ini untuk meningkatkan kesadaran tentang hak disabilitas dan aksesibilitas digital. Sehari-hari ia bekerja di sebuah startup health-tech, dan di waktu luangnya ia merawat kura-kura serta berkebun.
  twitter: rifatnajmi
  instagram: rifatnajmi
  linkedin: 'https://linkedin.com/in/rifatnajmi'
  website: 'https://rifatnajmi.com'
  avatar: 'rifat.webp'
nadija:
  name: Nadija Herdwina
  role: Koordinator strategi
  bio: Nadija adalah seorang desainer produk. Ia mengenal aksesibilitas digital di tahun 2021, dan mulai mendokumentasikan hasil eksplorasinya di X dan Substack melalui akun @aksesibiliti pada tahun 2025, dengan harapan semakin banyak desainer yang mulai sadar, belajar, dan berani maju mengadvokasi aksesibilitas digital :)
  twitter: aksesibiliti
  instagram: nadija.design
  linkedin: 'https://linkedin.com/in/nadijaherdwina'
  website: 'https://substack.com/@aksesibiliti'
  avatar: 'nadija.webp'
ocal:
  name: Muhammad Kautsar
  role: Koordinator konten
  bio: Ocal adalah seorang UX Research Writer di sebuah startup health-tech dengan minat tinggi pada layanan kesehatan, kesetaraan gender, dan dampak sosial. Ocal sedang mendalami bidang aksesibilitas digital dengan berkontribusi di Aksesibel.id sembari menulis kreatif dan kulineran di akhir pekan.
  instagram: phascolarc
  linkedin: 'https://www.linkedin.com/in/mkautsar/'
  avatar: 'ocal.webp'
fida:
  name: Alfida Zahra Firdausi
  role: Kontributor
  bio: Alfida adalah desainer produk di dunia edutech dengan pengalaman lebih dari tiga tahun. Tidak hanya itu, ia juga berada di dunia monetisasi dan F&B. Di sela sibuknya, ia selalu kembali pada buku, musik, dan tulisan — tempat di mana pikirannya berpulang.
  twitter: pikselperfek
  instagram: alfidazf
  linkedin: 'https://linkedin.com/in/alfidazf'
  medium: 'https://medium.com/@alfidazf'
  avatar: 'fida.webp'
alya:
  name: Alya Dhia Zahra
  role: Kontributor
  bio: Alya adalah UI/UX Designer sebuah perusahaan konsultasi di Jakarta. Ingin ikut membuat lebih banyak orang Indonesia menyadari pentingnya aksesibilitas digital. Mendalami topik ini di tahun 2024 melalui A11y Bootcamp Suarise & berpartisipasi sebagai mentor accessibility design challenge Suarise di tahun 2025. 
  twitter: ayladhia
  linkedin: 'https://www.linkedin.com/in/alyadz/'
  medium: 'https://medium.com/@ayladhia'
  avatar: 'alya.webp'
alfi:
  name: Alysia Alfi
  role: Kontributor
  bio: Building cool stuff on the web, one component at a time. Always down to chat about the latest in tech or help debug your div that`s mysteriously not centering.
  instagram: alysialfi
  linkedin: 'https://linkedin.com/in/alysialfi'
  medium: 'https://alysialfi.medium.com/'
  avatar: 'alfi.webp'
anggun:
  name: Anggun Cahya Ningrum
  role: Kontributor
  bio: Anggun adalah product designer berlatar belakang ilmu komputer dengan pengalaman lebih dari 5 tahun. Ia berkomitmen meningkatkan aksesibilitas untuk mengurangi kesenjangan kesempatan di Indonesia. Menonton film dan membaca buku adalah cara Anggun bersantai di waktu luangnya.
  tiktok: anggun_cahyaaa
  instagram: angguncahya
  linkedin: 'https://linkedin.com/in/angguncahya'
  website: 'https://angguncahya.framer.website/'
  avatar: 'anggun.webp'
silvi:
  name: Arianti Silvia
  role: Kontributor
  bio: Self-taught Product Designer (10+ YoE), CS background, former front-end developer. Designed every platforms and different businesses, for a few industries. Dog mom.
  twitter: riantisilvi
  instagram: riantisilvi
  linkedin: 'https://linkedin.com/in/riantisilvi'
  website: 'https://www.ariantisilvia.com'
  avatar: 'silvi.webp'
dian:
  name: Dian Anindya
  role: Kontributor
  bio: Individu yang suka mengerjakan hal-hal kreatif, eksperimen, dan meriset untuk bantu sekitar. Paling senang ketika membuat produk yang bisa bermanfaat dan dipakai oleh banyak orang.
  twitter: 
  instagram: dianinprmdt
  linkedin: 'https://linkedin.com/in/diananindyapramudito'
  website: 'https://diananindya.com'
  avatar: 'dian.webp'
fadhil:
  name: Fadhil Abdillah
  role: Kontributor
  bio: Fadhil here. 29 y.o with 7 year in digital produk designer. Product designer at AI Startup. This or next year want to pursue CPACC certificate like Mas Rifat. 
  twitter: fdmncfdmnc
  instagram: fadhilabdil
  linkedin: 'https://linkedin.com/in/fadhilabdillah'
  medium: 'https://medium.com/@works.fadhil'
  avatar: 'fadhil.webp'
keziah:
  name: Keziah Cahya Virdayanti
  role: Kontributor
  bio: Keziah adalah seorang product designer & researcher yang saat ini sedang mengambil jeda karier untuk fokus mengasuh anak. Ia memiliki ketertarikan terhadap isu disabilitas dan bisa berbahasa isyarat Indonesia (BISINDO). Di sela kesibukannya sebagai ibu rumah tangga, ia gemar membaca, menulis, dan menonton film. 
  twitter: keziahcahya
  instagram: keziahcahya
  linkedin: 'https://linkedin.com/in/keziahcv'
  website: 'https://keziahcahya.com'
  avatar: 'keziah.webp'
sekar:
  name: Madeleine Sekar Putri W
  role: Kontributor
  bio: Sekar adalah seorang software engineer yang sedang belajar mendalami isu aksesibilitas dan inklusivitas teknologi. Di waktu luang, Sekar suka menghabiskan waktunya untuk mempelajari berbagai hal baru dan mencoba ragam kuliner.
  instagram: madeleinesekar
  linkedin: 'https://linkedin.com/in/madeleinesekar'
  medium: 'https://medium.com/@madeleine.sekar'
  avatar: 'sekar.webp'
sarai:
  name: Sarifadhilah Aziz
  role: Kontributor
  bio: Sebagian besar ketertarikannya adalah pada literatur, filosofi dan kopi. Sekarang sedang menyelesaikan kuliah di Magister Psikologi karena kekagumannya pada hal-hal yang mendasari manusia berpikir dan perilaku.
  linkedin: 'https://id.linkedin.com/in/sarifadhilah-aziz-a12657299'
  avatar: 'sarai.webp'