fida:
  name: Alfida Zahra Firdausi
  role: Konten
  bio: Alfida adalah desainer produk di dunia edutech dengan pengalaman lebih dari tiga tahun. Tidak hanya itu, ia juga berada di dunia monetisasi dan F&B. Di sela sibuknya, ia selalu kembali pada buku, musik, dan tulisan — tempat di mana pikirannya berpulang.
  twitter: pikselperfek
  instagram: alfidazf
  linkedin: 'https://linkedin.com/in/alfidazf'
  website: 'https://medium.com/@alfidazf'
  avatar: 'fida.webp'
alya:
  name: Alya Dhia Zahra
  role: Konten
  bio: Alya adalah UI/UX Designer sebuah perusahaan konsultasi di Jakarta. Ingin ikut membuat lebih banyak orang Indonesia menyadari pentingnya aksesibilitas digital. Mendalami topik ini di tahun 2024 melalui A11y Bootcamp Suarise & berpartisipasi sebagai mentor accessibility design challenge Suarise di tahun 2025. 
  twitter: ayladhia
  linkedin: 'https://www.linkedin.com/in/alyadz/'
  website: 'https://medium.com/@ayladhia'
  avatar: 'alya.webp'
alfi:
  name: Alysia Alfi
  role: Konten dan web dev
  bio: 
  twitter: 
  instagram: 
  linkedin: 'https://linkedin.com/in/'
  website: 'https://.com'
  avatar: 'alfi.webp'
anggun:
  name: Anggun Cahya Ningrum
  role: Konten dan strategi
  bio: Anggun adalah product designer berlatar belakang ilmu komputer dengan pengalaman lebih dari 5 tahun. Ia berkomitmen meningkatkan aksesibilitas untuk mengurangi kesenjangan kesempatan di Indonesia. Menonton film dan membaca buku adalah cara Anggun bersantai di waktu luangnya.
  tiktok: anggun_cahyaaa
  instagram: angguncahya
  linkedin: 'https://linkedin.com/in/angguncahya'
  website: 'https://angguncahya.framer.website/'
  avatar: 'anggun.webp'
silvi:
  name: Arianti Silvia
  role: Konten, strategi, dan ilustrasi 
  bio: Self-taught Product Designer (10+ YoE), CS background, former front-end developer. Designed every platforms and different businesses, for a few industries. Dog mom.
  twitter: riantisilvi
  instagram: riantisilvi
  linkedin: 'https://linkedin.com/in/riantisilvi'
  website: 'https://www.ariantisilvia.com'
  avatar: 'silvi.webp'
dian:
  name: Dian Anindya
  role: Konten dan strategi
  bio: 
  twitter: 
  instagram: 
  linkedin: 'https://linkedin.com/in/'
  website: 'https://.com'
  avatar: 'dian.webp'
fadhil:
  name: Fadhil Abdillah
  role: Strategi dan ilustrasi
  bio: Fadhil here. 29 y.o with 7 year in digital produk designer. Product designer at AI Startup. This or next year want to pursue CPACC certificate like mas Rifat. 
  twitter: fdmncfdmnc
  instagram: fadhilabdil
  linkedin: 'https://linkedin.com/in/fadhilabdillah'
  website: 'https://medium.com/@works.fadhil'
  avatar: 'fadhil.webp'
keziah:
  name: Keziah Cahya Virdayanti
  role: Konten, strategi, dan ilustrasi
  bio: Keziah adalah seorang product designer & researcher yang saat ini sedang mengambil jeda karier untuk fokus mengasuh anak. Ia memiliki ketertarikan terhadap isu disabilitas dan bisa berbahasa isyarat Indonesia (BISINDO). Di sela kesibukannya sebagai ibu rumah tangga, ia gemar membaca, menulis, dan menonton film. 
  twitter: keziahcahya
  instagram: keziahcahya
  linkedin: 'https://linkedin.com/in/keziahcv'
  website: 'https://keziahcahya.com'
  avatar: 'keziah.webp'
sekar:
  name: Madeleine Sekar Putri W
  role: Konten dan webdev
  bio: 
  twitter: 
  instagram: 
  linkedin: 'https://linkedin.com/in/'
  website: 'https://.com'
  avatar: 'sekar.webp'
ocal:
  name: Muhammad Kautsar
  role: Konten dan strategi
  bio: UX Research Writer
  instagram: phascolarc
  linkedin: 'https://www.linkedin.com/in/mkautsar/'
  avatar: 'ocal.webp'
nadija:
  name: Nadija Herdwina Putri Soerojo
  role: Konten, strategi, dan ilustrasi
  bio: 
  twitter: 
  instagram: 
  linkedin: 'https://linkedin.com/in/'
  website: 'https://.com'
  avatar: 'nadija.webp'
rifat:
  name: Rifat Najmi
  role: Inisiator, kontributor
  bio: Rifat adalah desainer produk dan profesional aksesibilitas bersertifikasi CPACC dari IAAP. Ia menginisiasi situs ini untuk meningkatkan kesadaran tentang hak disabilitas dan aksesibilitas digital. Sehari-hari ia bekerja di sebuah startup health-tech, dan di waktu luangnya ia merawat kura-kura serta berkebun.
  twitter: rifatnajmi
  instagram: rifatnajmi
  linkedin: 'https://linkedin.com/in/rifatnajmi'
  website: 'https://rifatnajmi.com'
  avatar: 'rifat.webp'
sarai:
  name: Sarifadhilah Aziz
  role: Kontributor
  bio: 
  twitter: 
  instagram: 
  linkedin: 'https://linkedin.com/in/'
  website: 'https://.com'
  avatar: 'sarai.webp'